version: '3'
services:
  app:
    container_name: employee-svc-app
    build: .
    ports: 
      - ${APPORT}:4321 
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    depends_on:
      - db
    networks:
      - backend
  
  db:
    image: postgres:alpine
    container_name: employee-svc-db
    environment:
      - POSTGRES_USER=${DB_USER}  
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST} 
    ports:
      - "${DB_PORT}:5432"
    restart: on-failure
    volumes:
      - sql:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  api:
    driver: local
  sql:
    driver: local

networks:
  backend:
    driver: bridge

